name: Update Instagram IPs

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        shell: powershell
        run: |
          ./generate_ips.ps1

      - name: Commit & Push if changed
        shell: bash
        run: |
          git config user.name "bot"
          git config user.email "bot@example.com"

          git add instagram_ips.txt

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "update ips"
          git push
